name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev

      - name: Install Buildozer and Cython
        run: pip3 install --user --upgrade buildozer cython

      # هذا السطر هو الحل السحري ليوافق buildozer على الرخص تلقائياً
      - name: Build APK
        env:
          BUILDOZER_ACCEPT_SDK_LICENSE: 1
        run: |
          rm -rf .buildozer
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
