name: Build Android App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev libtinfo6

    - name: Install Buildozer
      run: pip3 install --upgrade buildozer cython virtualenv

    # إزالة خطوة sdkmanager لأن buildozer يقوم بتثبيت الـ SDK تلقائياً عند الحاجة
    
    - name: Build with Buildozer
      # تم تصحيح طريقة كتابة الـ log-level
      run: buildozer android debug --log-level 2
